# Generated by Django 5.1.1 on 2024-12-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethicalgovernance',
            name='resolution_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='governanceimprovement',
            name='progress_status',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50),
        ),
        migrations.AlterField(
            model_name='governancestructure',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='governancestructure',
            name='review_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leadershipaccountability',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='performancereporting',
            name='review_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], max_length=50),
        ),
        migrations.AlterField(
            model_name='purposeandvalues',
            name='review_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], max_length=50),
        ),
        migrations.AlterField(
            model_name='resourcemanagement',
            name='compliance_status',
            field=models.CharField(choices=[('Compliant', 'Compliant'), ('Partially Compliant', 'Partially Compliant'), ('Non-Compliant', 'Non-Compliant')], max_length=50),
        ),
        migrations.AlterField(
            model_name='riskandcompliance',
            name='compliance_status',
            field=models.CharField(choices=[('Compliant', 'Compliant'), ('Partially Compliant', 'Partially Compliant'), ('Non-Compliant', 'Non-Compliant')], max_length=50),
        ),
        migrations.AlterField(
            model_name='riskandcompliance',
            name='review_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], max_length=50),
        ),
        migrations.AlterField(
            model_name='riskandcompliance',
            name='risk_severity',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stakeholderengagement',
            name='resolution_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='strategicdirection',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='strategicdirection',
            name='review_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], max_length=50),
        ),
    ]
