# setup services

# docker compose version
version: '3.9'

# services
services:
  djangoserver:
    container_name: backend
    build:
      context: .
    command: >
      sh -c "python manage.py makemigrations && 
              python manage.py migrate && 
              python manage.py runserver 0.0.0.0:8000"    
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
      - ollama
    networks:
      - main_net
  db:
    container_name: database
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: iam-django
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - main_net

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    networks:
      - main_net
    volumes:
      - ollama_data:/root/.ollama # Persist Ollama data
    command: ["ollama", "run", "deepseek-r1:1.5b"] # Proper way to pass the command

    

volumes:
  postgres_data:
  ollama_data:

networks:
  main_net:
    driver: bridge