# Generated by Django 5.1.1 on 2024-12-10 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0007_group_alter_staff_department_staff_group_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BCMDocumentManagement',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_title', models.CharField(max_length=255)),
                ('upload_date', models.DateField(blank=True, null=True)),
                ('version', models.CharField(max_length=50)),
                ('document_type', models.CharField(max_length=255)),
                ('associated_plans', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('access_permissions', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('file_link', models.URLField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='BCMGovernance',
            fields=[
                ('governance_id', models.AutoField(primary_key=True, serialize=False)),
                ('bcm_policy_title', models.CharField(max_length=255)),
                ('roles_and_responsibilities', models.TextField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], max_length=50)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('review_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], max_length=50)),
                ('supporting_documents', models.FileField(upload_to='governance_documents/')),
                ('review_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('approver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_governance', to='main_app.staff')),
                ('governance_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_governance', to='main_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='BCMProgramReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=255)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('key_findings', models.TextField(blank=True, null=True)),
                ('compliance_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], max_length=50)),
                ('improvement_recommendations', models.TextField(blank=True, null=True)),
                ('implementation_plan', models.TextField(blank=True, null=True)),
                ('follow_up_actions', models.TextField(blank=True, null=True)),
                ('supporting_documents', models.FileField(upload_to='review_documents/')),
                ('comments', models.TextField(blank=True, null=True)),
                ('reviewer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessContinuityPlan',
            fields=[
                ('bcp_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=255)),
                ('business_function', models.CharField(max_length=255)),
                ('recovery_steps', models.TextField(blank=True, null=True)),
                ('contact_list', models.TextField(blank=True, null=True)),
                ('activation_criteria', models.TextField(blank=True, null=True)),
                ('testing_schedule', models.TextField(blank=True, null=True)),
                ('last_test_date', models.DateField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('plan_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessImpactAnalysis',
            fields=[
                ('bia_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_function', models.CharField(max_length=255)),
                ('impact_level', models.CharField(max_length=50)),
                ('dependencies', models.TextField(blank=True, null=True)),
                ('maximum_tolerable_downtime', models.IntegerField(blank=True, null=True)),
                ('recovery_time_objective', models.IntegerField(blank=True, null=True)),
                ('critical_resources', models.TextField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('impact_description', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='ContinuityRiskAssessment',
            fields=[
                ('risk_assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('risk_name', models.CharField(max_length=255)),
                ('impact_likelihood', models.CharField(max_length=50)),
                ('risk_severity', models.CharField(max_length=50)),
                ('associated_bcp', models.TextField(blank=True, null=True)),
                ('mitigation_plan', models.TextField(blank=True, null=True)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('review_cycle', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], max_length=50)),
                ('supporting_documents', models.FileField(upload_to='risk_documents/')),
                ('comments', models.TextField(blank=True, null=True)),
                ('risk_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='ContinuityStrategy',
            fields=[
                ('strategy_id', models.AutoField(primary_key=True, serialize=False)),
                ('strategy_name', models.CharField(max_length=255)),
                ('recovery_objective', models.TextField(blank=True, null=True)),
                ('resources_required', models.TextField(blank=True, null=True)),
                ('third_party_dependencies', models.TextField(blank=True, null=True)),
                ('associated_business_functions', models.TextField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], max_length=50)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('review_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('reviewer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='ContinuityTesting',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_scenario', models.TextField(blank=True, null=True)),
                ('test_date', models.DateField(blank=True, null=True)),
                ('participants', models.TextField(blank=True, null=True)),
                ('test_results', models.TextField(blank=True, null=True)),
                ('issues_identified', models.TextField(blank=True, null=True)),
                ('improvement_plan', models.TextField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('next_scheduled_test', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentActivationLog',
            fields=[
                ('incident_id', models.AutoField(primary_key=True, serialize=False)),
                ('incident_type', models.CharField(max_length=255)),
                ('date_activated', models.DateField(blank=True, null=True)),
                ('bcp_activated', models.BooleanField(blank=True, null=True)),
                ('resources_mobilized', models.TextField(blank=True, null=True)),
                ('status_updates', models.TextField(blank=True, null=True)),
                ('closure_date', models.DateField(blank=True, null=True)),
                ('lessons_learned', models.TextField(blank=True, null=True)),
                ('supporting_documents', models.FileField(upload_to='incident_documents/')),
                ('comments', models.TextField(blank=True, null=True)),
                ('decision_maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='CrisisCommunication',
            fields=[
                ('communication_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient_groups', models.TextField(blank=True, null=True)),
                ('message_template', models.TextField(blank=True, null=True)),
                ('date_sent', models.DateField(blank=True, null=True)),
                ('acknowledgment_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], max_length=50)),
                ('follow_up_required', models.BooleanField(blank=True, null=True)),
                ('escalation_plan', models.TextField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('attachments', models.FileField(upload_to='communication_attachments/')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff')),
                ('incident_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcm.incidentactivationlog')),
            ],
        ),
    ]
