# Generated by Django 5.1.1 on 2024-12-07 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualPlanning',
            fields=[
                ('planning_id', models.AutoField(primary_key=True, serialize=False)),
                ('audit_year', models.IntegerField()),
                ('high_level_scope', models.TextField()),
                ('expectations_identified', models.BooleanField()),
                ('impact_assessment_criteria', models.TextField()),
                ('audit_committee_comments', models.TextField()),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AuditPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('finalized_date', models.DateField()),
                ('approved_by', models.CharField(max_length=255)),
                ('objectives', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('finding_id', models.IntegerField()),
                ('action_description', models.TextField()),
                ('responsible_person', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ObservationMemo',
            fields=[
                ('memo_id', models.AutoField(primary_key=True, serialize=False)),
                ('observation_details', models.TextField()),
                ('severity', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50)),
                ('prepared_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEngagement',
            fields=[
                ('engagement_id', models.AutoField(primary_key=True, serialize=False)),
                ('engagement_type', models.CharField(choices=[('Operational', 'Operational'), ('Financial', 'Financial'), ('IT', 'IT')], max_length=50)),
                ('scheduled_start_date', models.DateTimeField()),
                ('scheduled_end_date', models.DateTimeField()),
                ('resources_allocated', models.TextField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iam.auditplan')),
            ],
        ),
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('findings_summary', models.TextField()),
                ('recommendations', models.TextField()),
                ('management_response', models.TextField()),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iam.auditengagement')),
            ],
        ),
        migrations.CreateModel(
            name='ExitMeeting',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting_summary', models.TextField()),
                ('management_response', models.TextField()),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iam.auditengagement')),
            ],
        ),
        migrations.CreateModel(
            name='Fieldwork',
            fields=[
                ('fieldwork_id', models.AutoField(primary_key=True, serialize=False)),
                ('observation_details', models.TextField()),
                ('evidence', models.FileField(upload_to='evidence/')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Reviewed', 'Reviewed'), ('Closed', 'Closed')], max_length=50)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iam.auditengagement')),
            ],
        ),
        migrations.CreateModel(
            name='DataCollection',
            fields=[
                ('collection_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_type', models.CharField(choices=[('Interview', 'Interview'), ('Testing', 'Testing')], max_length=50)),
                ('data_details', models.TextField()),
                ('collected_by', models.CharField(max_length=255)),
                ('fieldwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iam.fieldwork')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpPlan',
            fields=[
                ('follow_up_id', models.AutoField(primary_key=True, serialize=False)),
                ('implementation_status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=50)),
                ('follow_up_date', models.DateField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iam.correctiveaction')),
            ],
        ),
        migrations.CreateModel(
            name='ManagementResponse',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('response_details', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Addressed', 'Addressed')], max_length=50)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iam.auditreport')),
            ],
        ),
        migrations.CreateModel(
            name='QualityReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_date', models.DateField()),
                ('reviewer_name', models.CharField(max_length=255)),
                ('findings', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iam.auditreport')),
            ],
        ),
        migrations.CreateModel(
            name='RiskIdentification',
            fields=[
                ('risk_id', models.AutoField(primary_key=True, serialize=False)),
                ('process_id', models.IntegerField()),
                ('risk_description', models.TextField()),
                ('likelihood', models.IntegerField()),
                ('impact', models.IntegerField()),
                ('owner', models.CharField(max_length=255)),
                ('prioritization_status', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iam.annualplanning')),
            ],
        ),
        migrations.AddField(
            model_name='auditplan',
            name='linked_risks',
            field=models.ManyToManyField(to='iam.riskidentification'),
        ),
        migrations.CreateModel(
            name='RiskRegister',
            fields=[
                ('register_id', models.AutoField(primary_key=True, serialize=False)),
                ('priority_level', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50)),
                ('draft_review_status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Finalized', 'Finalized')], max_length=50)),
                ('comments', models.TextField()),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iam.riskidentification')),
            ],
        ),
        migrations.CreateModel(
            name='StakeholderCommunication',
            fields=[
                ('communication_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_details', models.TextField()),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Pending', 'Pending')], max_length=50)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iam.auditengagement')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPaper',
            fields=[
                ('work_paper_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('Interview Notes', 'Interview Notes'), ('Testing Results', 'Testing Results')], max_length=50)),
                ('content', models.FileField(upload_to='work_papers/')),
                ('prepared_by', models.CharField(max_length=255)),
                ('fieldwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iam.fieldwork')),
            ],
        ),
    ]
