# Generated by Django 5.1.1 on 2024-12-08 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskidentification',
            name='planning',
        ),
        migrations.RemoveField(
            model_name='auditengagement',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='fieldwork',
            name='engagement',
        ),
        migrations.RemoveField(
            model_name='stakeholdercommunication',
            name='engagement',
        ),
        migrations.RemoveField(
            model_name='exitmeeting',
            name='engagement',
        ),
        migrations.RemoveField(
            model_name='auditreport',
            name='engagement',
        ),
        migrations.RemoveField(
            model_name='auditplan',
            name='linked_risks',
        ),
        migrations.RemoveField(
            model_name='managementresponse',
            name='report',
        ),
        migrations.RemoveField(
            model_name='qualityreview',
            name='report',
        ),
        migrations.RemoveField(
            model_name='followupplan',
            name='action',
        ),
        migrations.RemoveField(
            model_name='datacollection',
            name='fieldwork',
        ),
        migrations.RemoveField(
            model_name='workpaper',
            name='fieldwork',
        ),
        migrations.DeleteModel(
            name='ObservationMemo',
        ),
        migrations.RemoveField(
            model_name='riskregister',
            name='risk',
        ),
        migrations.DeleteModel(
            name='AnnualPlanning',
        ),
        migrations.DeleteModel(
            name='StakeholderCommunication',
        ),
        migrations.DeleteModel(
            name='ExitMeeting',
        ),
        migrations.DeleteModel(
            name='AuditEngagement',
        ),
        migrations.DeleteModel(
            name='AuditPlan',
        ),
        migrations.DeleteModel(
            name='ManagementResponse',
        ),
        migrations.DeleteModel(
            name='AuditReport',
        ),
        migrations.DeleteModel(
            name='QualityReview',
        ),
        migrations.DeleteModel(
            name='CorrectiveAction',
        ),
        migrations.DeleteModel(
            name='FollowUpPlan',
        ),
        migrations.DeleteModel(
            name='DataCollection',
        ),
        migrations.DeleteModel(
            name='Fieldwork',
        ),
        migrations.DeleteModel(
            name='WorkPaper',
        ),
        migrations.DeleteModel(
            name='RiskIdentification',
        ),
        migrations.DeleteModel(
            name='RiskRegister',
        ),
    ]
