# Generated by Django 5.1.1 on 2024-12-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditplanning',
            name='allocated_resources',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditplanning',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditplanning',
            name='audit_frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditplanning',
            name='audit_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditplanning',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditplanning',
            name='key_risks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditplanning',
            name='planned_audits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditplanning',
            name='reviewer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditplanning',
            name='risk_assessment_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditreport',
            name='audit_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditreport',
            name='findings_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditreport',
            name='follow_up_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditreport',
            name='key_metrics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditreport',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditreport',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditreport',
            name='stakeholder_distribution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditresourceplanner',
            name='allocation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditresourceplanner',
            name='assigned_tasks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditresourceplanner',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditresourceplanner',
            name='engagement_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditresourceplanner',
            name='hours_allocated',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditresourceplanner',
            name='remaining_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditresourceplanner',
            name='skillset',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audituniverseregister',
            name='audit_frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audituniverseregister',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audituniverseregister',
            name='control_effectiveness',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audituniverseregister',
            name='last_audit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audituniverseregister',
            name='next_audit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audituniverseregister',
            name='risk_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compliancetracker',
            name='audit_finding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compliancetracker',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compliancetracker',
            name='corrective_actions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compliancetracker',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compliancetracker',
            name='last_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compliancetracker',
            name='regulation_reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compliancetracker',
            name='review_frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentmanagement',
            name='access_permissions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentmanagement',
            name='associated_risks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentmanagement',
            name='audit_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentmanagement',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentmanagement',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentmanagement',
            name='upload_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentmanagement',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engagementplanning',
            name='assigned_auditors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engagementplanning',
            name='milestones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engagementplanning',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engagementplanning',
            name='objectives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engagementplanning',
            name='planned_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engagementplanning',
            name='planned_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engagementplanning',
            name='risk_focus_areas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engagementplanning',
            name='scope',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='audit_criteria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='collected_evidence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='engagement_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='exceptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='findings_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='follow_up_required',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='root_cause_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='action_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='audit_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='effectiveness_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='reviewer_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fraudinvestigationlog',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fraudinvestigationlog',
            name='corrective_actions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fraudinvestigationlog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fraudinvestigationlog',
            name='evidence_collected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fraudinvestigationlog',
            name='resolution_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fraudinvestigationlog',
            name='root_cause',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualityassurance',
            name='action_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualityassurance',
            name='assessment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualityassurance',
            name='audit_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualityassurance',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualityassurance',
            name='improvement_opportunities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualityassurance',
            name='review_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualityassurance',
            name='reviewer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskmapping',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskmapping',
            name='control_effectiveness',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskmapping',
            name='documentation_links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskmapping',
            name='linked_controls',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskmapping',
            name='mapped_risks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskmapping',
            name='owner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskmapping',
            name='reviewed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskmapping',
            name='update_frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='risktrendsreport',
            name='associated_audits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='risktrendsreport',
            name='improvement_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='risktrendsreport',
            name='metrics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='risktrendsreport',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='risktrendsreport',
            name='recurring_issues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='risktrendsreport',
            name='root_causes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='risktrendsreport',
            name='trend_analysis_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
