# Generated by Django 5.1.1 on 2024-12-08 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0004_alter_auditplanning_allocated_resources_and_more'),
        ('main_app', '0007_group_alter_staff_department_staff_group_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditplanning',
            name='reviewer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff'),
        ),
        migrations.AlterField(
            model_name='auditreport',
            name='audit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iam.auditplanning'),
        ),
        migrations.AlterField(
            model_name='auditresourceplanner',
            name='engagement_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iam.engagementplanning'),
        ),
        migrations.AlterField(
            model_name='documentmanagement',
            name='audit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iam.auditplanning'),
        ),
        migrations.AlterField(
            model_name='engagementplanning',
            name='assigned_auditors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff'),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='engagement_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iam.engagementplanning'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='audit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iam.auditplanning'),
        ),
        migrations.AlterField(
            model_name='qualityassurance',
            name='audit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iam.auditplanning'),
        ),
        migrations.AlterField(
            model_name='qualityassurance',
            name='reviewer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff'),
        ),
        migrations.AlterField(
            model_name='riskmapping',
            name='owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff'),
        ),
    ]
