# Generated by Django 5.1.1 on 2024-12-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0010_alter_compliancetracker_assigned_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditplanning',
            name='audit_frequency',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='audituniverseregister',
            name='audit_frequency',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compliancetracker',
            name='review_frequency',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='riskmapping',
            name='update_frequency',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], max_length=50, null=True),
        ),
    ]
