# Generated by Django 5.1.1 on 2024-12-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0011_alter_auditplanning_audit_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityassurance',
            name='compliance_status',
            field=models.CharField(choices=[('Compliant', 'Compliant'), ('Partially Compliant', 'Partially Compliant'), ('Non-Compliant', 'Non-Compliant')], max_length=50),
        ),
    ]
