# Generated by Django 5.1.1 on 2024-12-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0012_alter_qualityassurance_compliance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancetracker',
            name='compliance_status',
            field=models.CharField(choices=[('Compliant', 'Compliant'), ('Partially Compliant', 'Partially Compliant'), ('Non-Compliant', 'Non-Compliant')], max_length=50),
        ),
    ]
