# Generated by Django 5.1.1 on 2025-01-06 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0013_alter_compliancetracker_compliance_status'),
        ('main_app', '0013_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditreport',
            name='audit_id',
        ),
        migrations.RemoveField(
            model_name='auditreport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='auditresourceplanner',
            name='engagement_id',
        ),
        migrations.RemoveField(
            model_name='audituniverseregister',
            name='risk_owner',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='audit_id',
        ),
        migrations.RemoveField(
            model_name='qualityassurance',
            name='audit_id',
        ),
        migrations.RemoveField(
            model_name='compliancetracker',
            name='assigned_owner',
        ),
        migrations.RemoveField(
            model_name='engagementplanning',
            name='assigned_auditors',
        ),
        migrations.RemoveField(
            model_name='executionlog',
            name='engagement_id',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='fraudinvestigationlog',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='qualityassurance',
            name='reviewer_id',
        ),
        migrations.RemoveField(
            model_name='riskmapping',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='risktrendsreport',
            name='owner',
        ),
        migrations.CreateModel(
            name='AuditAssessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=255)),
                ('scope', models.TextField(blank=True, null=True)),
                ('objectives', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('assigned_team', models.ManyToManyField(blank=True, null=True, to='main_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='AuditFollowUp',
            fields=[
                ('follow_up_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=255)),
                ('issues_resolved', models.TextField(blank=True, null=True)),
                ('corrective_actions', models.TextField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('follow_up_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='AuditNotification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=255)),
                ('audit_scope', models.TextField(blank=True, null=True)),
                ('objectives', models.TextField(blank=True, null=True)),
                ('audit_timeline', models.TextField(blank=True, null=True)),
                ('notification_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('auditee_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='AuditPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('audit_year', models.IntegerField(blank=True, null=True)),
                ('entity_name', models.CharField(max_length=255)),
                ('audit_frequency', models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], max_length=50, null=True)),
                ('priority_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=50)),
                ('allocated_resources', models.TextField(blank=True, null=True)),
                ('audit_schedule', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('assigned_team', models.ManyToManyField(blank=True, null=True, to='main_app.staff')),
            ],
        ),
        migrations.RenameModel(
            old_name='DocumentManagement',
            new_name='DocumentsManagement',
        ),
        migrations.CreateModel(
            name='AuditUniverse',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=255)),
                ('risk_category', models.CharField(choices=[('Operational', 'Operational'), ('Strategic', 'Strategic'), ('Financial', 'Financial'), ('Compliance', 'Compliance')], default='Operational', max_length=50)),
                ('priority_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=50)),
                ('last_audit_date', models.DateField(blank=True, null=True)),
                ('next_audit_date', models.DateField(blank=True, null=True)),
                ('audit_cycle_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('assigned_auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff')),
            ],
        ),
        migrations.AlterField(
            model_name='documentsmanagement',
            name='audit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iam.audituniverse'),
        ),
        migrations.CreateModel(
            name='DraftReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=255)),
                ('findings', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('draft_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('drafted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='EntranceMeeting',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=255)),
                ('discussion_points', models.TextField(blank=True, null=True)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('participants', models.ManyToManyField(blank=True, null=True, to='main_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='ExitMeeting',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=255)),
                ('discussion_points', models.TextField(blank=True, null=True)),
                ('agreed_actions', models.TextField(blank=True, null=True)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('participants', models.ManyToManyField(blank=True, null=True, to='main_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=255)),
                ('feedback_details', models.TextField(blank=True, null=True)),
                ('survey_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('auditee_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='FinalReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=255)),
                ('findings_summary', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='ObservationSheet',
            fields=[
                ('observation_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=255)),
                ('observation_details', models.TextField(blank=True, null=True)),
                ('impact', models.TextField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='OtherNotes',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=255)),
                ('note_details', models.TextField(blank=True, null=True)),
                ('note_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('risk_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=255)),
                ('risk_type', models.CharField(choices=[('Operational', 'Operational'), ('Strategic', 'Strategic'), ('Financial', 'Financial'), ('Compliance', 'Compliance')], default='Operational', max_length=50)),
                ('inherent_risk', models.IntegerField(blank=True, null=True)),
                ('residual_risk', models.IntegerField(blank=True, null=True)),
                ('control_effectiveness', models.TextField(blank=True, null=True)),
                ('assessed_date', models.DateField(blank=True, null=True)),
                ('risk_severity', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='SubRiskAssessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_process_name', models.CharField(max_length=255)),
                ('entity_name', models.CharField(max_length=255)),
                ('risk_category', models.CharField(choices=[('Operational', 'Operational'), ('Strategic', 'Strategic'), ('Financial', 'Financial'), ('Compliance', 'Compliance')], default='Operational', max_length=50)),
                ('inherent_risk', models.IntegerField(blank=True, null=True)),
                ('residual_risk', models.IntegerField(blank=True, null=True)),
                ('control_effectiveness', models.TextField(blank=True, null=True)),
                ('assessed_date', models.DateField(blank=True, null=True)),
                ('risk_severity', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='AuditProgram',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=255)),
                ('procedures', models.TextField(blank=True, null=True)),
                ('tests', models.TextField(blank=True, null=True)),
                ('program_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('assigned_auditors', models.ManyToManyField(blank=True, null=True, to='main_app.staff')),
                ('sub_process_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iam.subriskassessment')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingPaper',
            fields=[
                ('working_paper_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=255)),
                ('audit_task', models.CharField(max_length=255)),
                ('evidence_collected', models.TextField(blank=True, null=True)),
                ('task_completion_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff')),
            ],
        ),
        migrations.DeleteModel(
            name='AuditPlanning',
        ),
        migrations.DeleteModel(
            name='AuditReport',
        ),
        migrations.DeleteModel(
            name='AuditResourcePlanner',
        ),
        migrations.DeleteModel(
            name='AuditUniverseRegister',
        ),
        migrations.DeleteModel(
            name='ComplianceTracker',
        ),
        migrations.DeleteModel(
            name='EngagementPlanning',
        ),
        migrations.DeleteModel(
            name='ExecutionLog',
        ),
        migrations.DeleteModel(
            name='FollowUp',
        ),
        migrations.DeleteModel(
            name='FraudInvestigationLog',
        ),
        migrations.DeleteModel(
            name='QualityAssurance',
        ),
        migrations.DeleteModel(
            name='RiskMapping',
        ),
        migrations.DeleteModel(
            name='RiskTrendsReport',
        ),
    ]
