# Generated by Django 5.1.1 on 2025-01-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0014_remove_auditreport_audit_id_and_more'),
        ('main_app', '0013_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditassessment',
            name='assigned_team',
            field=models.ManyToManyField(blank=True, to='main_app.staff'),
        ),
        migrations.AlterField(
            model_name='auditplan',
            name='assigned_team',
            field=models.ManyToManyField(blank=True, to='main_app.staff'),
        ),
        migrations.AlterField(
            model_name='auditprogram',
            name='assigned_auditors',
            field=models.ManyToManyField(blank=True, to='main_app.staff'),
        ),
        migrations.AlterField(
            model_name='entrancemeeting',
            name='participants',
            field=models.ManyToManyField(blank=True, to='main_app.staff'),
        ),
        migrations.AlterField(
            model_name='exitmeeting',
            name='participants',
            field=models.ManyToManyField(blank=True, to='main_app.staff'),
        ),
    ]
