# Generated by Django 5.1.1 on 2025-01-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0015_alter_auditassessment_assigned_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audituniverse',
            name='audit_scope',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audituniverse',
            name='entity_type',
            field=models.CharField(choices=[('Process', 'Process'), ('Unit', 'Unit'), ('Program', 'Program'), ('Service Line', 'Service Line'), ('Function', 'Function')], default='Process', max_length=50),
        ),
        migrations.AddField(
            model_name='audituniverse',
            name='location_category',
            field=models.CharField(choices=[('Headquarters', 'Headquarters'), ('Regional Office', 'Regional Office'), ('Local Office', 'Local Office')], default='Headquarters', max_length=50),
        ),
        migrations.AddField(
            model_name='audituniverse',
            name='organizational_category',
            field=models.CharField(choices=[('Departmen', 'Department'), ('Division', 'Division'), ('Business Unit', 'Business Unit')], default='Department', max_length=50),
        ),
        migrations.AddField(
            model_name='audituniverse',
            name='process_category',
            field=models.CharField(choices=[('Procurement', 'Procurement'), ('Asset Management', 'Asset Management'), ('Financial Reporting', 'Financial Reporting')], default='Procurement', max_length=50),
        ),
        migrations.AddField(
            model_name='audituniverse',
            name='risk_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audituniverse',
            name='senior_manager_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audituniverse',
            name='strategic_relevance',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=50),
        ),
    ]
