# Generated by Django 5.1.1 on 2025-01-12 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0017_alter_audituniverse_organizational_category'),
        ('main_app', '0013_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessUnderstanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='auditprogram',
            name='sub_process_name',
        ),
        migrations.RemoveField(
            model_name='auditprogram',
            name='assigned_auditors',
        ),
        migrations.AddField(
            model_name='auditprogram',
            name='analytics_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auditprogram',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvedby', to='main_app.staff'),
        ),
        migrations.AddField(
            model_name='auditprogram',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditprogram',
            name='conducted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_by', to='main_app.staff'),
        ),
        migrations.AddField(
            model_name='auditprogram',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditprogram',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=50),
        ),
        migrations.AddField(
            model_name='auditprogram',
            name='test_results',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditprogram',
            name='work_paper_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workingpaper',
            name='analytics',
            field=models.CharField(choices=[('Manual', 'Manual'), ('CAAT', 'CAAT')], default='Manual', max_length=50),
        ),
        migrations.AddField(
            model_name='workingpaper',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workingpaper',
            name='observation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workingpaper',
            name='observation_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workingpaper',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='main_app.staff'),
        ),
        migrations.AddField(
            model_name='workingpaper',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_by', to='main_app.staff'),
        ),
        migrations.AddField(
            model_name='workingpaper',
            name='sample_justification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workingpaper',
            name='scope',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workingpaper',
            name='task_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workingpaper',
            name='test_conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workingpaper',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_by', to='main_app.staff'),
        ),
        migrations.CreateModel(
            name='control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
                ('performed_date', models.DateField(blank=True, null=True)),
                ('control_location', models.CharField(blank=True, max_length=255, null=True)),
                ('control_class', models.CharField(choices=[('Operational', 'Operational'), ('Strategic', 'Strategic'), ('Financial', 'Financial'), ('Compliance', 'Compliance')], default='Operational', max_length=50)),
                ('control_type', models.CharField(choices=[('Preventive', 'Preventive'), ('Detective', 'Detective'), ('Concurrent', 'Concurrent')], default='Preventive', max_length=50)),
                ('final_decision', models.BooleanField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff')),
                ('process_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iam.processunderstanding')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=255)),
                ('requirements_list', models.TextField(blank=True, null=True)),
                ('requested_from', models.CharField(blank=True, max_length=255, null=True)),
                ('date_requested', models.DateField(blank=True, null=True)),
                ('reminder_date', models.DateField(blank=True, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('escalation', models.BooleanField(blank=True, null=True)),
                ('sla', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('escalation_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_to', to='main_app.staff')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_by', to='main_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='SubProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('process_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iam.processunderstanding')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('risk_score', models.IntegerField(blank=True, null=True)),
                ('risk_type', models.CharField(choices=[('Operational', 'Operational'), ('Strategic', 'Strategic'), ('Financial', 'Financial'), ('Compliance', 'Compliance')], default='Operational', max_length=50)),
                ('subprocess_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iam.subprocess')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('subprocess_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iam.subprocess')),
            ],
        ),
        migrations.AddField(
            model_name='auditprogram',
            name='subprocess_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iam.subprocess'),
        ),
        migrations.DeleteModel(
            name='SubRiskAssessment',
        ),
    ]
