# Generated by Django 5.1.1 on 2025-01-12 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0018_processunderstanding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='process_id',
        ),
        migrations.AddField(
            model_name='control',
            name='subprocess_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iam.subprocess'),
        ),
    ]
