# Generated by Django 5.1.1 on 2025-01-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0020_alter_control_control_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='control_location',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
