# Generated by Django 5.1.1 on 2025-01-12 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0021_alter_control_control_location'),
        ('main_app', '0013_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirementslist',
            old_name='requirements_list',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='requirementslist',
            old_name='entity_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='requirementslist',
            name='status',
            field=models.CharField(blank=True, choices=[('Not Yet Shared', 'Not Yet Shared'), ('Partially Received', 'Partially Received'), ('Fully Received', 'Fully Received')], default='Not Yet Shared', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='AuditProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvedby', to='main_app.staff')),
                ('conducted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_by', to='main_app.staff')),
                ('subprocess_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iam.subprocess')),
            ],
        ),
        migrations.CreateModel(
            name='AuditTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('Partially Completed', 'Partially Completed'), ('Completed', 'Completed')], default='Open', max_length=50)),
                ('result', models.TextField(blank=True, null=True)),
                ('subprocess_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iam.subprocess')),
            ],
        ),
        migrations.AddField(
            model_name='requirementslist',
            name='test_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iam.audittest'),
        ),
        migrations.DeleteModel(
            name='AuditProgram',
        ),
    ]
