# Generated by Django 5.1.1 on 2025-01-12 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0022_rename_requirements_list_requirementslist_description_and_more'),
        ('main_app', '0013_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditprocedure',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='audittest',
            name='tested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff'),
        ),
        migrations.AlterField(
            model_name='audittest',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Partially Completed', 'Partially Completed'), ('Completed', 'Completed')], default='Not Started', max_length=50),
        ),
    ]
