# Generated by Django 5.1.1 on 2025-01-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0023_remove_auditprocedure_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementslist',
            name='escalation_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
