# Generated by Django 5.1.1 on 2025-01-19 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0024_alter_requirementslist_escalation_to'),
        ('main_app', '0013_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audituniverse',
            name='next_audit_date',
        ),
        migrations.RemoveField(
            model_name='audituniverse',
            name='senior_manager_feedback',
        ),
        migrations.AddField(
            model_name='auditassessment',
            name='team_members',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='team_members',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='auditassessment',
            name='assigned_team',
        ),
        migrations.RemoveField(
            model_name='auditplan',
            name='assigned_team',
        ),
        migrations.RemoveField(
            model_name='entrancemeeting',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='exitmeeting',
            name='participants',
        ),
        migrations.AddField(
            model_name='auditassessment',
            name='assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.staff'),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.staff'),
        ),
        migrations.AddField(
            model_name='entrancemeeting',
            name='participants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exitmeeting',
            name='participants',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
