# Generated by Django 5.1.1 on 2025-01-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0025_remove_audituniverse_next_audit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audituniverse',
            name='process_category',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
