# Generated by Django 5.1.1 on 2025-01-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0026_alter_audituniverse_process_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditplan',
            name='objectives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='scope',
            field=models.TextField(blank=True, null=True),
        ),
    ]
