# Generated by Django 5.1.1 on 2025-01-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0027_auditplan_objectives_auditplan_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='controls',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditplan',
            name='audit_frequency',
            field=models.CharField(blank=True, choices=[('1 Time', '1 Time'), ('2 Times', '2 Times'), ('3 Times', '3 Times')], default='1 Time', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='control_effectiveness',
            field=models.CharField(choices=[('Effective', 'Effective'), ('Not Effective', 'Not Effective')], default='Effective', max_length=50),
        ),
    ]
