# Generated by Django 5.1.1 on 2024-11-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_notificationstaff_notificationuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='descripton',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
