# Generated by Django 5.1.1 on 2024-12-29 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_staff_group_department_org_chart_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Select the parent department with a higher org_chart_level.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='main_app.department'),
        ),
    ]
