# Generated by Django 5.1.1 on 2024-12-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_department_key_external_relationships_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='session',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
