# Generated by Django 5.1.1 on 2024-12-31 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_user_session_delete_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='Key_external_relationships',
            new_name='annual_budget_section',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='key_customer_relationships',
            new_name='authority_delegation_section',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='key_interfaces',
            new_name='challenges_section',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='key_suppliers',
            new_name='departmental_swot_section',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='major_systems_and_data_used',
            new_name='governance_section',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='primary_responsibilities',
            new_name='interaction_section',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='purpose',
            new_name='introduction_section',
        ),
        migrations.AddField(
            model_name='department',
            name='mis_section',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='other_information_section',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='performance_section',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='plans_section',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='policies_section',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='primary_responsibilities_section',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='raci_matrix_section',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='regulations_section',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='team_section',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='technology_section',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(blank=True, choices=[('Data Entry', 'Data Entry'), ('Reviewer', 'Reviewer'), ('Approver', 'Approver')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Submit', 'Submit'), ('Review', 'Review'), ('Approve', 'Approve'), ('Reject', 'Reject')], max_length=50, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.staff')),
            ],
        ),
    ]
