# Generated by Django 5.1.1 on 2024-12-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_rename_key_external_relationships_department_annual_budget_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1, max_length=2),
        ),
    ]
