# Generated by Django 5.1.1 on 2024-11-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='workflow_status',
            field=models.CharField(choices=[('new', 'New'), ('define', 'Define Risk'), ('assessment', 'Risk Assessment'), ('completed', 'Completed')], default='new', max_length=50),
        ),
    ]
