# Generated by Django 5.1.1 on 2024-11-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0002_risk_workflow_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='risk',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='workflow_status',
            field=models.CharField(choices=[('new', 'New'), ('define', 'Define'), ('assessment', 'Assessment'), ('completed', 'Completed')], default='new', max_length=20),
        ),
    ]
