# Generated by Django 5.1.1 on 2024-11-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0004_risk_assessment_approval_status_and_more'),
        ('main_app', '0007_group_alter_staff_department_staff_group_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='department',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='strategic_importance',
        ),
        migrations.AddField(
            model_name='objective',
            name='progress_status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Started', max_length=50),
        ),
        migrations.RemoveField(
            model_name='objective',
            name='kpis_linked',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='owner',
        ),
        migrations.AddField(
            model_name='objective',
            name='kpis_linked',
            field=models.ManyToManyField(null=True, to='erm.kpi'),
        ),
        migrations.AddField(
            model_name='objective',
            name='owner',
            field=models.ManyToManyField(null=True, to='main_app.staff'),
        ),
    ]
