# Generated by Django 5.1.1 on 2024-11-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0006_alter_objective_kpis_linked_alter_objective_owner'),
        ('main_app', '0007_group_alter_staff_department_staff_group_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='owner',
            field=models.ManyToManyField(related_name='owners', to='main_app.staff'),
        ),
    ]
