# Generated by Django 5.1.1 on 2024-11-29 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0007_alter_objective_owner'),
        ('main_app', '0007_group_alter_staff_department_staff_group_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objective',
            name='owner',
        ),
        migrations.AddField(
            model_name='objective',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.department'),
        ),
    ]
