# Generated by Django 5.1.1 on 2024-11-29 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0009_alter_objective_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskass',
            old_name='impact_score',
            new_name='risk_score',
        ),
        migrations.RenameField(
            model_name='riskdefine',
            old_name='owner',
            new_name='identified_by',
        ),
        migrations.RemoveField(
            model_name='riskass',
            name='likelihood_score',
        ),
        migrations.RemoveField(
            model_name='riskass',
            name='risk_value',
        ),
        migrations.AddField(
            model_name='riskass',
            name='impact_rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
        migrations.AddField(
            model_name='riskass',
            name='likelihood_rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
        migrations.AddField(
            model_name='riskdefine',
            name='identification_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='riskdefine',
            name='impact',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
        migrations.AddField(
            model_name='riskdefine',
            name='likelihood',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
        migrations.AddField(
            model_name='riskdefine',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riskdefine',
            name='source',
            field=models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], default='Internal', max_length=50),
        ),
        migrations.AddField(
            model_name='riskdefine',
            name='subcategory',
            field=models.CharField(blank=1, max_length=255, null=1),
            preserve_default=1,
        ),
    ]
