# Generated by Django 5.1.1 on 2024-11-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0010_rename_impact_score_riskass_risk_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskass',
            name='mitigation_actions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='riskass',
            name='residual_risk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riskass',
            name='reviewer_comments',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='riskass',
            name='risk_heatmap_position',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=50),
        ),
    ]
