# Generated by Django 5.1.1 on 2024-11-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0011_riskass_mitigation_actions_riskass_residual_risk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskdefine',
            old_name='risk_type',
            new_name='category',
        ),
    ]
