# Generated by Django 5.1.1 on 2024-11-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0013_riskprioritization'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='prioritization_approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
