# Generated by Django 5.1.1 on 2024-11-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0014_risk_prioritization_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='workflow_status',
            field=models.CharField(choices=[('new', 'New'), ('define', 'Define'), ('assessment', 'Assessment'), ('prioritization', 'Prioritization'), ('completed', 'Completed')], default='new', max_length=20),
        ),
    ]
