# Generated by Django 5.1.1 on 2024-11-29 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0015_alter_risk_workflow_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskprioritization',
            old_name='assessed_to',
            new_name='assigned_to',
        ),
    ]
