# Generated by Django 5.1.1 on 2024-11-29 19:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0016_rename_assessed_to_riskprioritization_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskdefine',
            name='identification_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
