# Generated by Django 5.1.1 on 2024-11-29 20:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0017_alter_riskdefine_identification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='response_approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='risk',
            name='workflow_status',
            field=models.CharField(choices=[('new', 'New'), ('define', 'Define'), ('assessment', 'Assessment'), ('prioritization', 'Prioritization'), ('response', 'Response'), ('completed', 'Completed')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='RiskResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_strategy', models.CharField(choices=[('Avoid', 'Avoid'), ('Mitigate', 'Mitigate'), ('Transfer', 'Transfer'), ('Accept', 'Accept')], default='Avoid', max_length=50)),
                ('ActionPlan', models.TextField(null=True)),
                ('responsible_party', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('progress_status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Started', max_length=50)),
                ('resources_required', models.TextField(null=True)),
                ('effectiveness_review', models.TextField(null=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('risk', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='response_step', to='erm.risk')),
            ],
        ),
    ]
