# Generated by Django 5.1.1 on 2024-12-02 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0018_risk_response_approval_status_and_more'),
        ('main_app', '0007_group_alter_staff_department_staff_group_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingStructure',
            fields=[
                ('StructureID', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=255)),
                ('RoleName', models.CharField(max_length=255)),
                ('Responsibilities', models.TextField(blank=True, null=True)),
                ('RiskOwnership', models.JSONField(blank=True, null=True)),
                ('ReportingHierarchy', models.TextField(blank=True, null=True)),
                ('ApprovalMatrix', models.JSONField(blank=True, null=True)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('BudgetAllocated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('KPITracking', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oversight',
            fields=[
                ('OversightID', models.AutoField(primary_key=True, serialize=False)),
                ('MeetingDate', models.DateTimeField(blank=True, null=True)),
                ('CommitteeMembers', models.JSONField(blank=True, null=True)),
                ('MeetingAgenda', models.TextField(blank=True, null=True)),
                ('DecisionsMade', models.TextField(blank=True, null=True)),
                ('ActionItems', models.JSONField(blank=True, null=True)),
                ('RiskTopicsDiscussed', models.JSONField(blank=True, null=True)),
                ('FollowUpActions', models.JSONField(blank=True, null=True)),
                ('SupportingDocuments', models.FileField(upload_to='documents/')),
                ('MeetingMinutes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskTalent',
            fields=[
                ('TalentID', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=255)),
                ('Role', models.CharField(max_length=255)),
                ('TrainingPrograms', models.JSONField(blank=True, null=True)),
                ('Certifications', models.JSONField(blank=True, null=True)),
                ('RiskExperienceYears', models.DecimalField(decimal_places=2, max_digits=5)),
                ('PerformanceMetrics', models.TextField(blank=True, null=True)),
                ('LastEvaluationDate', models.DateTimeField(blank=True, null=True)),
                ('SkillsGap', models.TextField(blank=True, null=True)),
                ('DevelopmentPlan', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoreValuesMonitoring',
            fields=[
                ('MonitoringID', models.AutoField(primary_key=True, serialize=False)),
                ('ViolationType', models.CharField(max_length=255)),
                ('ViolationDescription', models.TextField(blank=True, null=True)),
                ('IncidentDate', models.DateTimeField(blank=True, null=True)),
                ('ResolutionActions', models.TextField(blank=True, null=True)),
                ('ComplianceCheckDate', models.DateTimeField(blank=True, null=True)),
                ('ComplianceStatus', models.CharField(choices=[('Compliant', 'Compliant'), ('Non-Compliant', 'Non-Compliant')], max_length=15)),
                ('FollowUpRequired', models.BooleanField(default=False)),
                ('SupportingEvidence', models.FileField(upload_to='evidence/')),
                ('ReportedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='CultureSurvey',
            fields=[
                ('SurveyID', models.AutoField(primary_key=True, serialize=False)),
                ('SurveyTitle', models.CharField(max_length=255)),
                ('SurveyDate', models.DateTimeField(blank=True, null=True)),
                ('Questions', models.JSONField(blank=True, null=True)),
                ('Responses', models.JSONField(blank=True, null=True)),
                ('OverallScore', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ImprovementAreas', models.TextField(blank=True, null=True)),
                ('ComplianceIssues', models.BooleanField(blank=True, default=False, null=True)),
                ('SurveyFeedback', models.TextField(blank=True, null=True)),
                ('RespondentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.staff')),
            ],
        ),
    ]
