# Generated by Django 5.1.1 on 2024-12-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0019_operatingstructure_oversight_risktalent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturesurvey',
            name='Questions',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='culturesurvey',
            name='Responses',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operatingstructure',
            name='ApprovalMatrix',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operatingstructure',
            name='RiskOwnership',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oversight',
            name='ActionItems',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oversight',
            name='CommitteeMembers',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oversight',
            name='FollowUpActions',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oversight',
            name='RiskTopicsDiscussed',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='risktalent',
            name='Certifications',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='risktalent',
            name='TrainingPrograms',
            field=models.CharField(blank=True, null=True),
        ),
    ]
