# Generated by Django 5.1.1 on 2024-12-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0021_alter_oversight_meetingminutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oversight',
            name='SupportingDocuments',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
