# Generated by Django 5.1.1 on 2024-12-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0022_alter_oversight_supportingdocuments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oversight',
            name='SupportingDocuments',
            field=models.FileField(upload_to='media/'),
        ),
    ]
