# Generated by Django 5.1.1 on 2024-12-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0023_alter_oversight_supportingdocuments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oversight',
            name='SupportingDocuments',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
