# Generated by Django 5.1.1 on 2024-12-05 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0025_alter_corevaluesmonitoring_supportingevidence_and_more'),
        ('main_app', '0007_group_alter_staff_department_staff_group_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessContext',
            fields=[
                ('context_id', models.AutoField(primary_key=True, serialize=False)),
                ('internal_factors', models.TextField(blank=True, null=True)),
                ('external_factors', models.TextField(blank=True, null=True)),
                ('swot_strengths', models.TextField(blank=True, null=True)),
                ('swot_weaknesses', models.TextField(blank=True, null=True)),
                ('swot_opportunities', models.TextField(blank=True, null=True)),
                ('swot_threats', models.TextField(blank=True, null=True)),
                ('pestle_political', models.TextField(blank=True, null=True)),
                ('pestle_economic', models.TextField(blank=True, null=True)),
                ('pestle_social', models.TextField(blank=True, null=True)),
                ('pestle_technological', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StrategicEvaluation',
            fields=[
                ('evaluation_id', models.AutoField(primary_key=True, serialize=False)),
                ('strategy_details', models.TextField(blank=True, null=True)),
                ('linked_risks', models.TextField(blank=True, null=True)),
                ('alternative_strategies', models.TextField(blank=True, null=True)),
                ('impact_assessment', models.TextField(blank=True, null=True)),
                ('cost_benefit_analysis', models.TextField(blank=True, null=True)),
                ('kpis', models.TextField(blank=True, null=True)),
                ('evaluation_date', models.DateTimeField(blank=True, null=True)),
                ('evaluation_outcome', models.TextField(blank=True, null=True)),
                ('reviewer_comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='control',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='control',
            name='related_risk',
        ),
        migrations.RemoveField(
            model_name='controllog',
            name='related_control',
        ),
        migrations.RemoveField(
            model_name='controlassessment',
            name='related_control',
        ),
        migrations.RemoveField(
            model_name='controlassessment',
            name='assessed_by',
        ),
        migrations.RemoveField(
            model_name='controllog',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='inherentrisk',
            name='associated_objective',
        ),
        migrations.RemoveField(
            model_name='inherentrisk',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='risktolerance',
            name='related_risk',
        ),
        migrations.RemoveField(
            model_name='remediationaction',
            name='related_risk',
        ),
        migrations.RemoveField(
            model_name='keyriskindicator',
            name='related_risk',
        ),
        migrations.RemoveField(
            model_name='residualrisk',
            name='related_inherent_risk',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='risk',
        ),
        migrations.RemoveField(
            model_name='riskradar',
            name='related_risk',
        ),
        migrations.RemoveField(
            model_name='keymetric',
            name='related_kri',
        ),
        migrations.RemoveField(
            model_name='keyriskindicator',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='objectiveprogress',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='objectivestrategy',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='objectivestrategy',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='remediationaction',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='riskradar',
            name='related_action',
        ),
        migrations.RemoveField(
            model_name='residualrisk',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='residualriskassessment',
            name='related_residual_risk',
        ),
        migrations.RemoveField(
            model_name='residualriskassessment',
            name='assessed_by',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='assessed_by',
        ),
        migrations.RemoveField(
            model_name='riskradar',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='risktolerance',
            name='related_appetite',
        ),
        migrations.RenameField(
            model_name='objective',
            old_name='name',
            new_name='objective_name',
        ),
        migrations.RenameField(
            model_name='riskappetite',
            old_name='comment',
            new_name='deviation_actions',
        ),
        migrations.RenameField(
            model_name='riskappetite',
            old_name='description',
            new_name='linked_objectives',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='kpis_linked',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='priority_level',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='status',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='riskappetite',
            name='approving_authority',
        ),
        migrations.RemoveField(
            model_name='riskappetite',
            name='category',
        ),
        migrations.RemoveField(
            model_name='riskappetite',
            name='max_threshold',
        ),
        migrations.RemoveField(
            model_name='riskappetite',
            name='min_threshold',
        ),
        migrations.RemoveField(
            model_name='riskappetite',
            name='name',
        ),
        migrations.RemoveField(
            model_name='riskappetite',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='riskappetite',
            name='review_date',
        ),
        migrations.AddField(
            model_name='objective',
            name='kpis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objective',
            name='linked_risks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objective',
            name='responsible_parties',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskappetite',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskappetite',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff'),
        ),
        migrations.AddField(
            model_name='riskappetite',
            name='review_cycle',
            field=models.CharField(blank=True, choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annually', 'Annually')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='riskappetite',
            name='risk_appetite_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskappetite',
            name='risk_thresholds',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskappetite',
            name='risk_tolerance_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='riskappetite',
            name='supporting_evidence',
            field=models.FileField(blank=True, null=True, upload_to='risk_appetite_docs/'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='budget_allocated',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objective',
            name='progress_status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='objective',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ActionLog',
        ),
        migrations.DeleteModel(
            name='Control',
        ),
        migrations.DeleteModel(
            name='ControlAssessment',
        ),
        migrations.DeleteModel(
            name='ControlLog',
        ),
        migrations.DeleteModel(
            name='InherentRisk',
        ),
        migrations.DeleteModel(
            name='KeyMetric',
        ),
        migrations.DeleteModel(
            name='KeyRiskIndicator',
        ),
        migrations.DeleteModel(
            name='ObjectiveProgress',
        ),
        migrations.DeleteModel(
            name='ObjectiveStrategy',
        ),
        migrations.DeleteModel(
            name='RemediationAction',
        ),
        migrations.DeleteModel(
            name='ResidualRisk',
        ),
        migrations.DeleteModel(
            name='ResidualRiskAssessment',
        ),
        migrations.DeleteModel(
            name='RiskAssessment',
        ),
        migrations.DeleteModel(
            name='RiskRadar',
        ),
        migrations.DeleteModel(
            name='RiskTolerance',
        ),
    ]
