# Generated by Django 5.1.1 on 2024-12-05 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0026_businesscontext_strategicevaluation_and_more'),
        ('main_app', '0007_group_alter_staff_department_staff_group_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturesurvey',
            name='Questions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='culturesurvey',
            name='Responses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operatingstructure',
            name='RiskOwnership',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oversight',
            name='ActionItems',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oversight',
            name='CommitteeMembers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oversight',
            name='RiskTopicsDiscussed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='risktalent',
            name='Certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='risktalent',
            name='TrainingPrograms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ChangeAssessment',
            fields=[
                ('change_id', models.AutoField(primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], max_length=10)),
                ('change_description', models.TextField(blank=True, null=True)),
                ('affected_risks', models.TextField(blank=True, null=True)),
                ('impact_assessment', models.TextField(blank=True, null=True)),
                ('change_date', models.DateTimeField(blank=True, null=True)),
                ('response_actions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('responsible_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='ImprovementAction',
            fields=[
                ('improvement_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('target_completion_date', models.DateTimeField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20)),
                ('resources_allocated', models.TextField(blank=True, null=True)),
                ('success_criteria', models.TextField(blank=True, null=True)),
                ('progress_updates', models.TextField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff')),
                ('related_risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erm.risk')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_period', models.CharField(max_length=50)),
                ('kpis_assessed', models.TextField(blank=True, null=True)),
                ('target_values', models.TextField(blank=True, null=True)),
                ('actual_values', models.TextField(blank=True, null=True)),
                ('variance_analysis', models.TextField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('areas_for_improvement', models.TextField(blank=True, null=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erm.objective')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.staff')),
            ],
        ),
    ]
