# Generated by Django 5.1.1 on 2024-12-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0027_alter_culturesurvey_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatingstructure',
            name='RiskOwnership',
            field=models.CharField(blank=True, null=True),
        ),
    ]
