# Generated by Django 5.1.1 on 2024-12-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0028_alter_operatingstructure_riskownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oversight',
            name='MeetingMinutes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
