# Generated by Django 5.1.1 on 2024-12-23 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0031_alter_riskdefine_department_and_more'),
        ('main_app', '0007_group_alter_staff_department_staff_group_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskass',
            name='assessed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.staff'),
        ),
        migrations.AlterField(
            model_name='riskprioritization',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.staff'),
        ),
        migrations.RemoveField(
            model_name='riskresponse',
            name='responsible_party',
        ),
        migrations.AddField(
            model_name='riskresponse',
            name='responsible_party',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.staff'),
        ),
    ]
