# Generated by Django 5.1.1 on 2024-12-23 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0032_alter_riskass_assessed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskdefine',
            name='section',
        ),
        migrations.AlterField(
            model_name='riskdefine',
            name='objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erm.objective'),
        ),
    ]
