# Generated by Django 5.1.1 on 2024-12-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0033_remove_riskdefine_section_alter_riskdefine_objective'),
        ('main_app', '0007_group_alter_staff_department_staff_group_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskresponse',
            name='responsible_party',
            field=models.ManyToManyField(blank=True, to='main_app.staff'),
        ),
    ]
