# Generated by Django 5.1.1 on 2024-12-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0034_alter_riskresponse_responsible_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskass',
            name='reviewer_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskprioritization',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskresponse',
            name='ActionPlan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskresponse',
            name='effectiveness_review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskresponse',
            name='resources_required',
            field=models.TextField(blank=True, null=True),
        ),
    ]
