# Generated by Django 5.1.1 on 2024-12-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0035_alter_riskass_reviewer_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskass',
            name='risk_heatmap_position',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Severe', 'Severe')], default='Low', max_length=50),
        ),
    ]
