# Generated by Django 5.1.1 on 2024-12-28 10:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0037_riskdefine_risk_cause_riskdefine_risk_event_and_more'),
        ('main_app', '0007_group_alter_staff_department_staff_group_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='Residual_approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='risk',
            name='close_approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='RiskClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('close_date', models.DateField(default=django.utils.timezone.now)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.staff')),
                ('risk', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='close_step', to='erm.risk')),
            ],
        ),
        migrations.CreateModel(
            name='RiskResidualAss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField(default=django.utils.timezone.now)),
                ('likelihood_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('impact_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_heatmap_position', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Severe', 'Severe')], default='Low', max_length=50)),
                ('mitigation_actions', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewer_comments', models.TextField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.staff')),
                ('risk', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='residual_step', to='erm.risk')),
                ('risk_appetite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erm.riskappetite')),
            ],
        ),
    ]
