# Generated by Django 5.1.1 on 2024-12-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0038_risk_residual_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskclose',
            name='reviewer_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
