# Generated by Django 5.1.1 on 2024-12-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0039_riskclose_reviewer_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='workflow_status',
            field=models.CharField(choices=[('new', 'New'), ('define', 'Define'), ('assessment', 'Assessment'), ('prioritization', 'Prioritization'), ('response', 'Response'), ('residual', 'Residual'), ('close', 'Close'), ('completed', 'Completed')], default='new', max_length=20),
        ),
    ]
