# Generated by Django 5.1.1 on 2024-12-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0041_rename_residual_approval_status_risk_residual_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskresidualass',
            name='impact_rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
        migrations.AlterField(
            model_name='riskresidualass',
            name='likelihood_rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
    ]
