# Generated by Django 5.1.1 on 2024-12-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm', '0042_alter_riskresidualass_impact_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskass',
            name='impact_rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
        migrations.AlterField(
            model_name='riskass',
            name='likelihood_rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
        migrations.AlterField(
            model_name='riskdefine',
            name='impact',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
        migrations.AlterField(
            model_name='riskdefine',
            name='likelihood',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
    ]
